language: node_js #指定使用的语言

node_js: stable  #采用nodejs的最新版本

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

before_install:
    - export TZ='Asia/Shanghai' # 更改时区    

# Start: Build Lifecycle
install:
  - npm install

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo g
  - hexo algolia

# 指定博客分支
branches:
  only:
    - hexo #触发持续集成的分支

# 指定博客的仓库地址
env:
  global:
    - GH_REF: github.com/dgzd/dgzd.github.io.git

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
#   - cd ./public
#   - git init
  - git config user.name "dgz"
  - git config user.email "dgz19971210@gmail.com"
  - hexo deploy
#   - git add .
#   - git commit -m "travis auto deploy"
#   - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master