# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ding's Blog # your blog title name
subtitle: 记录、分享、学习   —— By 轻尘
author: 轻尘 # 作者
language: zh-CN
timezone: Asia/Shanghai

# custom Site settings
# more detail check out docs
# header-img://o7bkkhiex.bkt.clouddn.com/lion-blur-bg.jpg
SEOTitle: Ding's Blog 
header-img: /img/post-bg-coffee.jpeg
email: dgz19971210@gmail.com
description: "一个人静静享受着孤独"
keyword: 轻尘,Ding,ding # seo key words

favicon:  # your favicon png
# custom end

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ding.gq
root: /
# permalink: :year/:month/:day/:title/
# permalink: :posts/:category/:year-:month-:day-:title.html
permalink: :title.html
permalink_defaults:

# SNS settings
# RSS:
#weibo_username: 
#zhihu_username: dgz19971210
#github_username: dgzd
#twitter_username: dgz19971210
#jianshu_username: 96d93c8aec3b
#facebook_username: 100011668193436
#linkedin_username:  

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings 
disqus_username: dings-blog

# Duoshuo settings
duoshuo_username:  # 你的多说帐号
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# Use livere
use_livere:

# Analytics settings
# Baidu Analytics
ba_track_id: 960ff1a63fe6560d36e1793d804b529b
# Google Analytics
ga_track_id: UA-122001025-1    # Format: UA-xxxxxx-xx
ga_domain: ding.gq

# Sidebar settings
sidebar: true
sidebar-about-description: 若乃霾曀潜销，莫振莫竦；轻尘不飞，纤萝不动。 # 个人描述
sidebar-avatar:    # 头像


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  

# Category & Tag
default_category: uncategorized
category_map:
    Mac: Mac
    Linux: Linux
    运维: 运维
    终端: 终端
    Python: Python
    随笔: 随笔
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape


markdown:
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji


## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/dgzd/dgzd.github.io.git
  branch: master




# img CDN path
cdn-url:  # 你的CDN地址

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
clip-avatar: "?imageView2/2/w/300/h/300/interlace/1/q/90"
clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

# post default images
#post-default-img: /img/post-bg-coffee.jpeg  #博文默认的图片
#post-default-img-mobile: /img/home-bg-o.jpg #移动端显示的图片

# search api , set your custom key
swiftype_key: 


# archive page title 
archive:
    title: archives
    description: 可以根据归档日期检索所有文件

#search:                     # 实现文章搜索功能
#  path: search.xml
#  field: post
#  format: html
#  limit: 10000

symbols_count_time:
  symbols: true       # 文章字数
  time: true          # 阅读时长
  total_symbols: true # 所有文章总字数
  total_time: true    # 所有文章阅读总时长

sitemap:                    # 生成站点地图用于SEO优化
  path: sitemap.xml

baidusitmap:                # 同上
  path: baidusitemap.xml

# Algolia 搜索
algolia:
  applicationID: 'LEF5EMES60'
  indexName: 'Search'
  apiKey: 51179a44bb9bdc96dd14453b3050c3e2
  adminApiKey: 6be6e6139dfe8e842cf595ba0f05cb07
  chunkSize: 5000

# encrypt 加密
# password: Ding
# abstract: Welcome to my blog, enter password to read.
# message: Welcome to my blog, enter password to read.

encrypt:
    enable: true
    password: dkglze